import { Product, Package } from '@/types';

export const ZVEC_PHONE        = '+260973804982';
export const ZVEC_PHONE_DISPLAY = '+260 973 804 982';
export const ZVEC_WHATSAPP_URL  = 'https://wa.me/260973804982';

export const categories = [
  { id: 'all', name: 'All Products', icon: '🛒' },
  { id: 'refrigerators', name: 'Refrigerators & Freezers', icon: '🧊' },
  { id: 'televisions', name: 'Televisions & Entertainment', icon: '📺' },
  { id: 'cookers', name: 'Cookers & Stoves', icon: '🍳' },
  { id: 'kitchen', name: 'Kitchen Appliances', icon: '☕' },
  { id: 'laptops', name: 'Laptops & Computers', icon: '💻' },
  { id: 'mobile', name: 'Mobile Devices', icon: '📱' },
  { id: 'furniture', name: 'Furniture & Home', icon: '🛋️' },
  { id: 'student', name: 'Student & Office', icon: '📚' },
];

export const products: Product[] = [
  // Refrigerators
  {
    id: 'r001',
    name: 'Hisense 230L Double Door Refrigerator',
    slug: 'hisense-230l-double-door-fridge',
    category: 'refrigerators',
    price: 4800,
    originalPrice: 5500,
    image: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=600&q=80',
    description: 'Energy-efficient double door refrigerator with frost-free technology. Perfect for family use.',
    features: ['Frost Free', 'Energy Saving A+', '230L Capacity', '2 Year Warranty'],
    inStock: true,
    badge: 'Best Seller',
  },
  {
    id: 'r002',
    name: 'Samsung 150L Single Door Refrigerator',
    slug: 'samsung-150l-single-door-fridge',
    category: 'refrigerators',
    price: 2900,
    image: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&q=80',
    description: 'Compact and reliable single door refrigerator ideal for apartments and small families.',
    features: ['150L Capacity', 'Low Energy Consumption', 'Vegetable Box', '1 Year Warranty'],
    inStock: true,
  },
  {
    id: 'r003',
    name: 'LG 320L French Door Refrigerator',
    slug: 'lg-320l-french-door-fridge',
    category: 'refrigerators',
    price: 9200,
    originalPrice: 10500,
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80',
    description: 'Premium French door refrigerator with inverter technology and smart diagnosis.',
    features: ['Linear Inverter', 'Smart Diagnosis', '320L Capacity', '10 Year Compressor Warranty'],
    inStock: true,
    badge: 'Premium',
  },
  // Televisions
  {
    id: 't001',
    name: 'Hisense 43" 4K Smart TV',
    slug: 'hisense-43-4k-smart-tv',
    category: 'televisions',
    price: 3200,
    originalPrice: 3800,
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f4834c?w=600&q=80',
    description: '43-inch 4K Ultra HD Smart TV with built-in Wi-Fi and access to streaming apps.',
    features: ['4K Ultra HD', 'Smart TV', 'Wi-Fi Built-In', 'HDR10', '3 HDMI Ports'],
    inStock: true,
    badge: 'Popular',
  },
  {
    id: 't002',
    name: 'Samsung 55" QLED 4K TV',
    slug: 'samsung-55-qled-4k-tv',
    category: 'televisions',
    price: 7500,
    originalPrice: 8900,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    description: 'Stunning QLED display with Quantum Dot technology for vivid colors and deep contrast.',
    features: ['QLED Technology', '4K Resolution', 'Quantum Processor', 'Alexa Built-In'],
    inStock: true,
    badge: 'Premium',
  },
  {
    id: 't003',
    name: 'TCL 32" Full HD LED TV',
    slug: 'tcl-32-full-hd-led-tv',
    category: 'televisions',
    price: 1500,
    image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=600&q=80',
    description: 'Affordable Full HD television perfect for bedrooms and small living spaces.',
    features: ['Full HD 1080p', 'LED Display', 'USB Multimedia', '2 HDMI Ports'],
    inStock: true,
  },
  // Cookers
  {
    id: 'c001',
    name: 'Mika 4-Burner Gas Cooker',
    slug: 'mika-4-burner-gas-cooker',
    category: 'cookers',
    price: 2100,
    image: 'https://images.unsplash.com/photo-1556909172-8c2f041fca1e?w=600&q=80',
    description: 'Durable 4-burner gas cooker with auto ignition and oven. Ideal for Zambian cooking.',
    features: ['4 Gas Burners', 'Auto Ignition', 'Built-in Oven', 'Stainless Steel'],
    inStock: true,
    badge: 'Best Seller',
  },
  {
    id: 'c002',
    name: 'Ramtons 2-Plate Electric Cooker',
    slug: 'ramtons-2-plate-electric-cooker',
    category: 'cookers',
    price: 650,
    image: 'https://images.unsplash.com/photo-1586165368502-1bad197a6461?w=600&q=80',
    description: 'Portable 2-plate electric cooker perfect for students and small households.',
    features: ['2 Electric Plates', 'Compact Design', 'Easy to Clean', 'Adjustable Temperature'],
    inStock: true,
  },
  // Kitchen
  {
    id: 'k001',
    name: 'Blueflame Microwave Oven 20L',
    slug: 'blueflame-microwave-20l',
    category: 'kitchen',
    price: 1100,
    originalPrice: 1350,
    image: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=600&q=80',
    description: '20-litre microwave oven with multiple cooking modes and digital display.',
    features: ['20L Capacity', 'Digital Display', '700W Power', 'Auto Defrost'],
    inStock: true,
  },
  {
    id: 'k002',
    name: 'Kenwood Stand Mixer',
    slug: 'kenwood-stand-mixer',
    category: 'kitchen',
    price: 1800,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80',
    description: 'Professional stand mixer with multiple attachments for all your baking needs.',
    features: ['800W Motor', '5L Bowl', '5 Speed Settings', 'Multiple Attachments'],
    inStock: true,
  },
  // Laptops
  {
    id: 'l001',
    name: 'Lenovo IdeaPad 15" Laptop',
    slug: 'lenovo-ideapad-15-laptop',
    category: 'laptops',
    price: 4500,
    originalPrice: 5200,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80',
    description: 'Reliable 15-inch laptop with Intel Core i5, 8GB RAM and 512GB SSD. Great for students and work.',
    features: ['Intel Core i5', '8GB RAM', '512GB SSD', 'Windows 11', '15.6" FHD Display'],
    inStock: true,
    badge: 'Popular',
  },
  {
    id: 'l002',
    name: 'HP Pavilion 14" Laptop',
    slug: 'hp-pavilion-14-laptop',
    category: 'laptops',
    price: 3800,
    image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=600&q=80',
    description: 'Slim and stylish HP Pavilion laptop with all-day battery life.',
    features: ['Intel Core i5', '8GB RAM', '256GB SSD', 'Windows 11', 'Backlit Keyboard'],
    inStock: true,
  },
  {
    id: 'l003',
    name: 'Acer Aspire 15" Budget Laptop',
    slug: 'acer-aspire-15-budget-laptop',
    category: 'laptops',
    price: 2800,
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&q=80',
    description: 'Affordable entry-level laptop ideal for students and basic office tasks.',
    features: ['Intel Celeron', '4GB RAM', '128GB SSD', 'Windows 11', '15.6" Display'],
    inStock: true,
    badge: 'Budget Pick',
  },
  // Mobile
  {
    id: 'm001',
    name: 'Samsung Galaxy A35 5G',
    slug: 'samsung-galaxy-a35-5g',
    category: 'mobile',
    price: 3200,
    originalPrice: 3600,
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&q=80',
    description: 'Mid-range 5G smartphone with 50MP camera and long-lasting 5000mAh battery.',
    features: ['5G Capable', '50MP Camera', '5000mAh Battery', '128GB Storage', 'Super AMOLED'],
    inStock: true,
    badge: 'New Arrival',
  },
  {
    id: 'm002',
    name: 'Tecno Spark 20 Pro',
    slug: 'tecno-spark-20-pro',
    category: 'mobile',
    price: 1600,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80',
    description: 'Feature-packed affordable smartphone with large display and powerful camera.',
    features: ['6.78" Display', '50MP Camera', '5000mAh Battery', '128GB Storage', 'Face Unlock'],
    inStock: true,
    badge: 'Best Value',
  },
  // Furniture
  {
    id: 'f001',
    name: '3-Seater Fabric Sofa Set',
    slug: '3-seater-fabric-sofa-set',
    category: 'furniture',
    price: 3500,
    originalPrice: 4200,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80',
    description: 'Comfortable 3-seater sofa set with durable fabric upholstery. Available in multiple colors.',
    features: ['3-Seater', 'Durable Fabric', 'Wooden Frame', 'Easy Assembly'],
    inStock: true,
  },
  {
    id: 'f002',
    name: 'Queen Size Bed Frame with Mattress',
    slug: 'queen-bed-frame-with-mattress',
    category: 'furniture',
    price: 4200,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80',
    description: 'Complete queen size bed frame with orthopedic mattress for a great night\'s sleep.',
    features: ['Queen Size', 'Orthopedic Mattress', 'Storage Drawers', 'Solid Wood'],
    inStock: true,
  },
  // Student & Office
  {
    id: 's001',
    name: 'Study Desk and Chair Set',
    slug: 'study-desk-chair-set',
    category: 'student',
    price: 1200,
    image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80',
    description: 'Ergonomic study desk and chair set perfect for students and home office use.',
    features: ['Spacious Desktop', 'Ergonomic Chair', 'Storage Shelf', 'Cable Management'],
    inStock: true,
  },
  {
    id: 's002',
    name: 'HP DeskJet Ink Advantage Printer',
    slug: 'hp-deskjet-ink-advantage-printer',
    category: 'student',
    price: 1450,
    image: 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=600&q=80',
    description: 'All-in-one printer with print, scan, and copy functions. Wireless enabled.',
    features: ['Print, Scan, Copy', 'Wireless', 'Mobile Printing', 'Automatic 2-Sided Print'],
    inStock: true,
  },
];

export const packages: Package[] = [
  {
    id: 'pkg001',
    title: 'Civil Servant Package',
    subtitle: 'Home Essentials Bundle',
    description: 'Designed for salaried civil servants, this bundle includes top household appliances at a special bundled price. Ideal for furnishing your home without breaking the bank.',
    targetAudience: 'Civil Servants & Government Workers',
    products: ['r001', 't001', 'c001'],
    totalValue: 10100,
    packagePrice: 8500,
    icon: '🏛️',
    color: 'blue',
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80',
  },
  {
    id: 'pkg002',
    title: 'Student Package',
    subtitle: 'Essential Study Kit',
    description: 'Everything a student needs to succeed academically. Laptop, printer, and study furniture at a price that works for students and their families.',
    targetAudience: 'University & College Students',
    products: ['l003', 's002', 's001'],
    totalValue: 5450,
    packagePrice: 4500,
    icon: '🎓',
    color: 'green',
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&q=80',
  },
  {
    id: 'pkg003',
    title: 'New Mother Package',
    subtitle: 'Baby & Home Essentials',
    description: 'A carefully selected bundle for new and expectant mothers. From kitchen appliances to home comfort — everything you need for your growing family.',
    targetAudience: 'New & Expectant Mothers',
    products: ['r002', 'k001', 'c002'],
    totalValue: 4650,
    packagePrice: 3900,
    icon: '👶',
    color: 'pink',
    image: 'https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=800&q=80',
  },
  {
    id: 'pkg004',
    title: 'New Home Package',
    subtitle: 'Complete Home Setup',
    description: 'Moving into a new home? Get everything you need in one order. Fridge, TV, cooker, sofa, and bed — delivered to your door.',
    targetAudience: 'New Homeowners & Newlyweds',
    products: ['r001', 't001', 'c001', 'f001', 'f002'],
    totalValue: 17600,
    packagePrice: 14500,
    icon: '🏠',
    color: 'orange',
    image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80',
  },
];

export const zambianProvinces = [
  'Central Province',
  'Copperbelt Province',
  'Eastern Province',
  'Luapula Province',
  'Lusaka Province',
  'Muchinga Province',
  'Northern Province',
  'North-Western Province',
  'Southern Province',
  'Western Province',
];

export const DELIVERY_FEES: Record<string, number> = {
  'Lusaka Province':       0,
  'Central Province':    100,
  'Copperbelt Province': 150,
  'Eastern Province':    200,
  'Luapula Province':    200,
  'Muchinga Province':   200,
  'Northern Province':   200,
  'North-Western Province': 200,
  'Southern Province':   150,
  'Western Province':    250,
};
